backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Order;
use yii\data\Pagination;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'orders', 'addtoarchive', 'delete', 'archive'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $last_id=Yii::$app->request->cookies->getValue('last_id');
        if(!$last_id)
            $last_id=0;
        $orders=Order::find()->orderBy('id DESC')->where(['archive'=>NULL])->andWhere(['>', 'id',$last_id])->limit(40)->all();
        return $this->render('index', [
            'orders'=>$orders
        ]);
    }


    public function actionOrders()
    {
        $orders=Order::find()->orderBy('id DESC')->where(['archive'=>NULL])->all();
        Yii::$app->response->cookies->add(new \yii\web\Cookie([
            'name' => 'last_id',
            'value' => $orders[0]->id,
        ]));
        return $this->render('orders',[
            'orders'=>$orders
        ]);
    }
    public function actionArchive()
    {
        $query=Order::find()->orderBy('id DESC')->where(['archive'=>1]);
        $pagination = new Pagination([
                'defaultPageSize'=>2,
                'totalCount'=>$query->count()
            ]);
        $orders=$query->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('archive',[
            'orders'=>$orders,
            'pagination'=>$pagination,
        ]);
    }
    public function actionAddtoarchive($id)
    {
        $order=Order::findOne(['id'=>$id]);
        $order->archive=1;
        $order->save();
        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionDelete($id)
    {
        $order=Order::findOne($id);
        $order->delete();
        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'main-login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте ваш почтовый ящик для продолжения.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Вы ошиблись при наборе почты.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }
    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = 'main-login';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль установлен.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public $layout = "mystock"; 
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /*public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    /*public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    /*public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    /*public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    /*public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    /*public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    /*public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    /*public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    /*public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    /*public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }*/
}

backend/views/yii2-app/site/archive.php
<?php 
    use yii\helpers\Html;
    use yii\helpers\Url;
    use common\models\Product;
    use yii\widgets\LinkPager;
    
$this->title = 'Заказы из архива';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row">
        <?php if(!empty($orders)) { foreach($orders as $order){?>
        <div class="col-md-5">
                        <ul class="list-group">
              <li class="list-group-item">
                <div>
                    <span style="margin-left:20px">Удалить: </span>
                    <?= Html::a('<span class="label label-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></span>', ['site/delete', 'id'=>$order->id], [
                        'data' => [
                            'confirm' => 'Вы уверенны, что хотите удалить этот заказ?',
                        ],
                    ]) ?>
                </div>
              </li>
              <li class="list-group-item"><b>id: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->id;?></li>
              <li class="list-group-item"><b>Имя: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->name;?></li>
              <li class="list-group-item"><b>Телефон: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->phone;?></li>
              <li class="list-group-item"><b>Город: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->city;?></li>
              <li class="list-group-item"><b>Новая почта: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->office;?></li>
              <li class="list-group-item"><b>Общая сумма: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->total;?></li>
              <li class="list-group-item">
                <table class="table table-striped" style="border: 1px solid #000;">
                    <tr>
                        <th>Товар</th>
                        <th>Код товара</th>
                        <th>Количество</th>
                        <th>Размер</th>
                    </tr>
                    <?php $p_ids=explode("##", $order->prod_ids);
                        $products=(new Product)->findProductsByOrderIds($p_ids);
                        $count_ids=explode("##",$order->prod_counts);
                        $size_ids=explode("##",$order->prod_sizes);
                        $i=0; foreach($products as $prod){
                    ?>
                    <tr>
                        <td><a href="<?=Url::toRoute(['/../main/product', 'alias'=>$prod['alias']]);?>"><?=$prod['name'];?></a><?php if (!$prod['name']) echo 'товар удален';?></td>
                        <td><?=$prod['code'];?></td>
                        <td><?=$count_ids[$i];?></td>
                        <td><?=$size_ids[$i];?></td>
                    </tr>
                    <?php $i++;}?>
                </table>
              </li>
            </ul>
        </div>
        <?php }  }?>
    </div>
        <?php if($pagination) {?>
    <div id="pages">
        <?=LinkPager::widget([
            'pagination'=>$pagination,
            'firstPageLabel'=>'В начало',
            'lastPageLabel'=>'В конец',
            'prevPageLabel'=>'&laquo;'
        ]);?>
    </div>
    <?php }?>
</div>

backend/views/yii2-app/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

backend/views/yii2-app/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\models\Product;
$this->title="Новые заказы";
?>
<?php if(!empty($orders)){?>
<div class="container">
    <div class="row">
        <?php  foreach($orders as $order){?>
        <div class="col-md-5">
            <ul class="list-group">
              <li class="list-group-item">
                <div>
                    <span>Доставленно (добавить в архив): </span><a href="<?=Url::toRoute(['site/addtoarchive', 'id'=>$order->id]);?>"><span class="label label-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></span></a>
                    <span style="margin-left:20px">Удалить: </span>
                    <?= Html::a('<span class="label label-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></span>', ['site/delete', 'id'=>$order->id], [
                        'data' => [
                            'confirm' => 'Вы уверенны, что хотите удалить этот заказ?',
                        ],
                    ]) ?>
                </div>
              </li>
              <li class="list-group-item"><b>id: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->id;?></li>
              <li class="list-group-item"><b>Имя: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->name;?></li>
              <li class="list-group-item"><b>Телефон: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->phone;?></li>
              <li class="list-group-item"><b>Город: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->city;?></li>
              <li class="list-group-item"><b>Новая почта: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->office;?></li>
              <li class="list-group-item"><b>Общая сумма: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->total;?></li>
              <li class="list-group-item">
                <table class="table table-striped" style="border: 1px solid #000;">
                    <tr>
                        <th>Товар</th>
                        <th>Код товара</th>
                        <th>Количество</th>
                        <th>Размер</th>
                    </tr>
                    <?php $p_ids=explode("##", $order->prod_ids);
                        $products=(new Product)->findProductsByOrderIds($p_ids);
                        $count_ids=explode("##",$order->prod_counts);
                        $size_ids=explode("##",$order->prod_sizes);
                        $i=0; foreach($products as $prod){
                    ?>
                    <tr>
                        <td><a href="<?=Url::toRoute(['/../main/product', 'alias'=>$prod['alias']]);?>"><?=$prod['name'];?></a><?php if (!$prod['name']) echo 'товар удален';?></td>
                        <td><?=$prod['code'];?></td>
                        <td><?=$count_ids[$i];?></td>
                        <td><?=$size_ids[$i];?></td>
                    </tr>
                    <?php $i++;}?>
                </table>
              </li>
            </ul>
        </div>
        <?php }?>
    </div>
    <a style="width:83%;" class="btn btn-success" href="<?=Url::toRoute(['site/orders']);?>">Все заказы</a>
</div>
<?php } else {?>
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-warning" style="text-align:center;" role="alert">Новых заказов пока что нету...</div>
        <a style="width:100%;" class="btn btn-success" href="<?=Url::toRoute(['site/orders']);?>">Все необработанные заказы</a>
    </div>
    </div>
<?php }?>

backend/views/yii2-app/site/login.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>
<div class="login-box">
    <div class="login-logo">
        <a href="#">Вход в Админ-панель</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Введите свои данные для входа</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>
        <div class="row"><div class="col-xs-8">
        <a href="<?=Url::to('request-password-reset')?>">Восстановить пароль</a>
        </div></div>
        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

backend/views/yii2-app/site/orders.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\models\Product;
$this->title="Необработанные заказы";
?>

<div class="container">
    <div class="row">
        <?php if(!empty($orders)) { foreach($orders as $order){?>
        <div class="col-md-5">
            <ul class="list-group">
              <li class="list-group-item">
                <div>
                    <span>Доставленно (добавить в архив): </span><a href="<?=Url::toRoute(['site/addtoarchive', 'id'=>$order->id]);?>"><span class="label label-success"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></span></a>
                    <span style="margin-left:20px">Удалить: </span>
                    <?= Html::a('<span class="label label-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></span>', ['site/delete', 'id'=>$order->id], [
                        'data' => [
                            'confirm' => 'Вы уверенны, что хотите удалить этот заказ?',
                        ],
                    ]) ?>
                </div>
              </li>
              <li class="list-group-item"><b>id: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->id;?></li>
              <li class="list-group-item"><b>Имя: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->name;?></li>
              <li class="list-group-item"><b>Телефон: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->phone;?></li>
              <li class="list-group-item"><b>Город: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->city;?></li>
              <li class="list-group-item"><b>Новая почта: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->office;?></li>
              <li class="list-group-item"><b>Общая сумма: </b><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> <?=$order->total;?></li>
              <li class="list-group-item">
                <table class="table table-striped" style="border: 1px solid #000;">
                    <tr>
                        <th>Товар</th>
                        <th>Код товара</th>
                        <th>Количество</th>
                        <th>Размер</th>
                    </tr>
                    <?php $p_ids=explode("##", $order->prod_ids);
                        $products=(new Product)->findProductsByOrderIds($p_ids);
                        $count_ids=explode("##",$order->prod_counts);
                        $size_ids=explode("##",$order->prod_sizes);
                        
                        $i=0; foreach($products as $prod){
                    ?>
                    <tr>
                        <td><a href="<?=Url::toRoute(['/../main/product', 'alias'=>$prod['alias']]);?>"><?=$prod['name'];?></a><?php if (!$prod['name']) echo 'товар удален';?></td>
                        <td><?=$prod['code'];?></td>
                        <td><?=$count_ids[$i];?></td>
                        <td><?=$size_ids[$i];?></td>
                    </tr>
                    <?php $i++;}?>
                </table>
              </li>
            </ul>
        </div>
        <?php }}?>
    </div>
</div>