common/models/Product.php
<?php

namespace common\models;
use yii\data\Pagination;
use common\models\ProductAttribute;
use common\models\ProductAttributeValue;
use yii\web\UploadedFile;
use Yii;

/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $amount
 * @property double $price
 * @property integer $discount
 * @property string $main_img
 * @property string $photos
 * @property string $desc
 * @property string $about_brand
 * @property integer $category_id
 * @property string $seo_title
 * @property string $seo_keys
 * @property string $sei_desc
 * @property string $alias
 *
 * @property Category $category
 */
class Product extends \yii\db\ActiveRecord
{
    public $increase_price;

    public $decrease_price;
    /**
     * @inheritdoc
     */

    public $productAttributeModel;
    public $productAttributeValueModel;

    public function __construct()
    {
        $this->productAttributeModel = new ProductAttribute();
        $this->productAttributeValueModel = new ProductAttributeValue();

        parent::__construct();
    }

    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'code', 'amount', 'price', 'category_id', 'attributes'], 'required'],
            [['amount', 'discount', 'category_id', 'top', 'featured', 'news', 'position'], 'integer'],
            [['price'], 'number'],
            [['desc', 'about_brand', 'seo_keys', 'seo_desc'], 'string'],
            [['name', 'code', 'seo_title', 'alias', 'made'], 'string', 'max' => 255],
            ['sizes', 'safe'],
            ['main_img','file','skipOnEmpty' => true, 'extensions' => 'png, jpg', 'checkExtensionByMimeType'=>false],
            [['photos'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg', 'maxFiles' => 20, 'checkExtensionByMimeType'=>false],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
    public function getAllAttributes()
    {
        $productAttributeModel = new ProductAttribute();
        $productAttributeValueModel = new ProductAttributeValue();

        $attributes = $productAttributeModel->getAll();

        $return = [];
        foreach ($attributes as $number => $attribute) {
            if (!$attribute->isEmptyAttribute($attribute->id)) {
                $return[] = $attribute;
            }
        }

        var_dump($return);

        return $return;
    } **/
    
    public $r_price;
    public function afterFind()
    {
        if($this->discount)
            $this->r_price=(1-$this->discount/100)*$this->price;
        else
            $this->r_price=$this->price;
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'positon'=>'Позиция',
            'code' => 'Код товара',
            'amount' => 'Наличие',
            'position'=>'Позиция',
            'sizes'=>'Размеры',
            'price' => 'Цена (в гривнах)',
            'discount' => 'Скидка (в процентах)',
            'main_img' => 'Главное фото',
            'photos' => 'Фотографии',
            'desc' => 'Описание товара',
            'about_brand' => 'О бренде',
            'category_id' => 'Категория',
            'seo_title' => 'Seo Заголовок',
            'seo_keys' => 'Seo Ключевые слова',
            'seo_desc' => 'Seo Описание',
            'alias' => 'name-url',
            'top' => 'Топ товар',
            'news' => 'Новинки',
            'made' => 'Производитель',
            'attributes' => 'Атрибуты',

            'increase_price' => 'Увеличить цену на все товары',
            'decrease_price' => 'Понизить цену на все товары',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
    public function getAllinAlias($id)
    {
        if ($id) {
            $query = static::find()->where(['category_id'=>$id])->distinct();
        } else {
            $query =static::find();
        }

        /** Pagination **/
        $pagination = new Pagination([
            'totalCount'        =>$query->count(),
            'defaultPageSize'   => 8
        ]);
            
        $query = $query->orderBy('position');
        $products = $query->offset($pagination->offset)->limit($pagination->limit)->all();

        return ['products'=>$products, 'pagination'=>$pagination];
    }
    
    public function getProd($alias)
    {
        $product = static::find()->where(['alias' => $alias])->one();//мы находимся и так в этом классе, грамотнее писать статик либо селф
        return $product;
    }
    
    public function getAll()
    {
        return static::find()->orderBy('position')->all();
    }
    
    public function findProductsByIds($ids)
    {
        $products=array();
        for($i=0;$i<count($ids);$i++)
            $products[]=self::find()->where(['id'=>$ids[$i]['id']])->one();
        return $products;
    }
    public function findProductsByOrderIds($ids)
    {
        $products=array();
        for($i=0;$i<count($ids);$i++)
            $products[]=static::find()->where(['id'=>$ids[$i]])->one();
        return $products;
    }
    public function getAllinSearch($q)
    {
        $query = static::find()
            ->leftJoin('category', '`category`.`id`=`product`.`category_id`')
            ->where(['like', 'product.name', $q])
            ->orWhere(['like', 'product.desc', $q])
            ->orWhere(['like', 'product.code', $q])
            ->orWhere(['like', 'product.alias', $q])
            ->orWhere(['like', 'category.name', $q])
            ->orWhere(['like', 'category.alias', $q])
            ->with('category')
            ->distinct();
        $pagination= new Pagination([
            'totalCount'=>$query->count(),//общее количество товаров
            'defaultPageSize'=>8//количесво товаров на одной странице
        ]);
        $products=$query->offset($pagination->offset)//смещение = текущая страница*defaultPageSize
            ->limit($pagination->limit)//лимит записей =defaultPageSize
            ->all();
        
        return ['products'=>$products, 'pagination'=>$pagination];
    }

    public function getFilterProduct($query)
    {
        $type = $query['type'];
        $id_category = $query['id'];
        switch ($type) {
            case 'attr':
                $products = $this->find()->where(['category_id' => $id_category])->all();

                $attr_id = $query['attr_id'];
                $attr_value_id = $query['attr_value_id'];
                foreach ($products as $number => $product) {
                    $attrs = json_decode($product->attributes);
                    $unset = true;
                    foreach ($attrs as $attr_number => $attr) {
                        if ($attr[0] == $attr_id && $attr[1] == $attr_value_id) {
                            $unset = false;
                            break;
                        }
                    }
                    if ($unset) {
                        unset($products[$number]);
                    }
                }
                break;
            case 'price':
                $products = $this->find()->where(['category_id' => $id_category])->orderBy('price DESC')->all();
                break;
            case 'category':
                $id_sub_category = $query['id_sub_category'];
                $products = $this->find()->where(['category_id' => $id_sub_category])->all();
                break;
            default:
                $products = $this->find()->where(['category_id' => $id_category])->all();
                break;
        }

        $pagination= new Pagination([
            'totalCount'=>count($products),//общее количество товаров
            'defaultPageSize'=>8//количесво товаров на одной странице
        ]);

        return ['products'=>$products, 'pagination'=>$pagination];
    }
    
    public function getTop()
    {
        return static::find()
        ->where(['top' => 1])
        ->orderBy('position')
        ->all();
    }

    public function getFeatured()
    {
        return static::find()
        ->where(['featured' => 1])
        ->orderBy('position')
        ->all();
    }

    public function getNews()
    {
        return static::find()
        ->where(['news' => 1])
        ->orderBy('position')
        ->all();
    }
}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Product;
use common\models\ProductAttribute;
use common\models\ProductSearch;
use common\models\ThemeSettings;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\imagine\Image;
use common\components\Translit;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends MyController
{
    /**
     * @inheritdoc
     */
    /*public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $product = new Product();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if ($product->load(Yii::$app->request->post())) {
            $post = Yii::$app->request->post()['Product'];
            
            /** change price */
            if (isset($post['price'])) {
                $object = $this->findModel($post['id']);
                $object->price = $post['price'];
                $object->save();
            }

            /** increase price */
            if (isset($post['increase_price']) && !empty($post['increase_price'])) {
                $object = $product->find()->all();

                foreach ($object as $number => $product) {
                    $product->price += $post['increase_price'];
                    $product->save();
                }
            }

            /** decrease_price */
            if (isset($post['decrease_price']) && !empty($post['decrease_price'])) {
                $object = $product->find()->all();

                foreach ($object as $number => $product) {

                    if ($product->price < $post['decrease_price'])
                        $product->price = 0;
                    else
                        $product->price -= $post['decrease_price'];

                    $product->save();
                }
            }
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'product' => $product,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();
        $modelTheme = ThemeSettings::findOne(['id'=>1]);
        $str="";

        if ($model->load(Yii::$app->request->post())) {
            $attributes = $model->attributes;

            if ($attributes) {
                foreach ($attributes as $number => $value) {
                    $attributes[$number] = explode(',', $value);
                }
            }

            $model->attributes = json_encode($attributes);
            //return $this->redirect(['view', 'id' => $model->id]);
            if(UploadedFile::getInstances($model, 'photos'))
            {
                $model->photos=UploadedFile::getInstances($model, 'photos');
                foreach ($model->photos as $file) {
                    $file->saveAs('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension);
                    Image::thumbnail('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension, 440, 420)->save(Yii::getAlias('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension), ['quality' => 50]);
                    $str.=$file->baseName.".".$file->extension."##";
                }
            }
            if(UploadedFile::getInstance($model, 'main_img'))
            {
                $model->main_img=UploadedFile::getInstance($model, 'main_img');
                $model->main_img->saveAs('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension);
                Image::thumbnail('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension, 440, 420)->save(Yii::getAlias('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension), ['quality' => 50]);
                $model->main_img=$model->main_img->baseName.".".$model->main_img->extension;
            }
            $model->photos=$str;
            $model->alias=(new Translit())->str2url($model->name);
            $model->sizes = '';// implode(", ", $model->sizes);
            //$model->alias=(new Product)->str2url($model->name);
            if ($model->save())
                return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model'         => $model,
                'model_theme'   => $modelTheme,
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if($model->photos)
        {
            $str=$model->photos;
        }
        else {
            $str='';
        }
        $img=$model->main_img;
        if ($model->load(Yii::$app->request->post())) {
            $model->sizes=implode(", ", $model->sizes);
            $attributes = $model->attributes;

            if ($attributes) {
                foreach ($attributes as $number => $value) {
                    $attributes[$number] = explode(',', $value);
                }
            }

            $model->attributes = json_encode($attributes);
            //return $this->redirect(['view', 'id' => $model->id]);
            if(UploadedFile::getInstances($model, 'photos'))
            {
                $model->photos=UploadedFile::getInstances($model, 'photos');
                if(!isset($str)) {$str="";}
                foreach ($model->photos as $file) {
                    $file->saveAs('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension);
                    Image::thumbnail('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension, 440, 420)->save(Yii::getAlias('../../frontend/web/mt/img/'.$file->baseName.".".$file->extension), ['quality' => 50]);
                    $str.=$file->baseName.".".$file->extension."##";
                }
            }
            if(UploadedFile::getInstance($model, 'main_img'))
            {
                $model->main_img=UploadedFile::getInstance($model, 'main_img');
                $model->main_img->saveAs('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension);
                Image::thumbnail('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension, 440, 420)->save(Yii::getAlias('../../frontend/web/mt/img/'.$model->main_img->baseName.".".$model->main_img->extension), ['quality' => 50]);
                $model->main_img=$model->main_img->baseName.".".$model->main_img->extension;
            }
            else
                $model->main_img=$img;
            $model->photos=$str;
            $model->alias=(new Translit())->str2url($model->name);
            //$model->alias=(new Product)->str2url($model->name);
            if ($model->save())
                return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    public function actionDeletephoto($id, $name)
    {
        $model = $this->findModel($id);
        $model->photos= str_replace ( $name."##", "", $model->photos);
        $model->save();
        return $this->redirect(['update', 'id' => $model->id]);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/yii2-app/product/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\widgets\Pjax;
use common\models\Category;
use dosamigos\ckeditor\CKEditor;
use common\models\Size;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */

?>
<style>
    .clear
    {
        clear: both;
    }
    .ph{
        float: left;
        position: relative;
    }
    .ph a
    {
        position: absolute;
        top: 0;
        right: 0;
        background-color: #fff;
        border: 1px solid #000;
    }
</style>
<?php Pjax::begin();?>
<div class="product-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'position')->textInput() ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <!-- categories -->
    <?php
        $categories = Category::find()->select(['name','id'])->indexBy('id')->column();
        $categories[0] = '--';
        $params = [
            //'prompt' => 'Выберите статус...',
            //'multiple' => 'true'
        ];
        asort($categories);
    ?>
    <?= $form->field($model, 'category_id')->dropDownList($categories); ?>
    <!-- /categories -->

    <!-- attributes -->
    <div class="attribute">
        <h4>Атрибуты товара</h4>
        <ul>
            <?php foreach ($model->productAttributeModel->getAll(false) as $number => $attribute): ?>
                <li>
                    <?php
                        $attributeValues = $attribute->productAttributeValueModel->find()->select(['value', 'id'])->where(['id_attribute' => $attribute->id])->indexBy('id')->column();

                        foreach ($attributeValues as $id => $value) {
                            $attributeValues[$attribute->id.','.$id] = $value;
                            unset($attributeValues[$id]);
                        }
                        $attributeValues['false'] = '--';
                        asort($attributeValues);
                    ?>
                    <?= $form->field($model, 'attributes[]')->dropDownList($attributeValues)->label($attribute->name); ?>
                </li>
            <?php endforeach; ?>
            <li><?= Html::a('Добавить новый аттрибут', ['product-attribute/create']); ?></li>
        </ul>
    </div>
    <!-- /attributes -->
    <style>
        .attribute ul {
            padding: 0;
        }
        .attribute ul > li{
            display: inline-block;
        }
    </style>
    
    <?= $form->field($model, 'top')->dropDownList([1=>'В топ товарах',0=>'Не в топ товарах']) ?>

     <?= $form->field($model, 'featured')->dropDownList([1=>'В рекомендуемых',0=>'Не в рекомендуемых']) ?>

     <?= $form->field($model, 'news')->dropDownList([1=>'В новинках',0=>'Не в новинках']) ?>

    <?= $form->field($model, 'amount')->dropDownList([1=>'В наличии',0=>'Не в наличии']) ?>
   
   <?= $form->field($model, 'made')->textInput() ?>

    <?= $form->field($model, 'sizes')->widget(Select2::className(), [
        'data' => Size::find()->select(['name'])->indexBy('name')->column(),
        'size' => Select2::MEDIUM,
        'options' => ['placeholder' => 'Выберите размеры...', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true,
        ],
        ]) ?>
    
    <?= $form->field($model, 'price')->textInput() ?>

    <?= $form->field($model, 'discount')->textInput() ?>
    
    <?php if($model->main_img){echo "<img style='width:100px;' src='../../frontend/web/mt/img/".$model->main_img."' alt='ph' />";}?>
    <?= $form->field($model, 'main_img')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => ['previewFileType' => 'image','showUpload' => false]
    ]); ?>
    
    <?php if($model->photos){
        $photos=explode("##", $model->photos);
        foreach ($photos as $photo){?>
            <?php if($photo){ ?>
            <div class="ph">
                <img style='width:100px;' src='../../frontend/web/mt/img/<?=$photo;?>'/>
                <a href="<?=Url::toRoute(['product/deletephoto', 'id'=>$model->id, 'name'=>trim($photo)]);?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
            </div>
            <?php }?>
    <?php } }?>
    <div class="clear"></div>
    <?= $form->field($model, 'photos[]')/*->fileInput(['multiple' => true, 'accept' => 'image/*']); */->widget(FileInput::classname(), [
        'options' => ['multiple' => true, 'accept' => 'image/*'],
        'pluginOptions' => ['previewFileType' => 'image','showUpload' => false,]
    ]); ?>

    <?= $form->field($model, 'desc')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
        ])   ?>

    <?= $form->field($model, 'about_brand')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
        ])   ?>

    <?= $form->field($model, 'seo_title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'seo_keys')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'seo_desc')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Запомнить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php Pjax::end();?>

backend/views/yii2-app/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'amount') ?>
    
    <?= $form->field($model, 'top') ?>

    <?= $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'discount') ?>

    <?php // echo $form->field($model, 'main_img') ?>

    <?php // echo $form->field($model, 'photos') ?>

    <?php // echo $form->field($model, 'desc') ?>

    <?php // echo $form->field($model, 'about_brand') ?>

    <?php // echo $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'seo_title') ?>

    <?php // echo $form->field($model, 'seo_keys') ?>

    <?php // echo $form->field($model, 'sei_desc') ?>

    <?php // echo $form->field($model, 'alias') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/yii2-app/product/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Product */

$this->title = 'Создание товара';
$this->params['breadcrumbs'][] = ['label' => 'Товары', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-create">


    <?= $this->render('_form', [
        'model'         => $model,
        'model_theme'   => $model_theme
    ]) ?>

</div>

backend/views/yii2-app/product/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use common\models\Category;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $searchModel common\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Товары';
$this->params['breadcrumbs'][] = $this->title;
$arr=[0=>'Нет в наличии', 1=>'В наличии'];
?>
<div class="product-index">
    <p>
        <?= Html::a('Добавить Товар', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin();?>
    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($product, 'increase_price')->textInput(['placeholder' => 'Введите фиксированную цену в грн.']) ?>
        <?= $form->field($product, 'decrease_price')->textInput(['placeholder' => 'Введите фиксированную цену в грн.']) ?>
        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']); ?>
        </div>
    <?php ActiveForm::end(); ?>
    <?php Pjax::end();?>
    
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            ['class' => 'yii\grid\ActionColumn'],
            'name',
            [
                'attribute' => 'price',
                'format' => 'text',
                'content' => function($data){
                    $string = '<form method="post" action="">';
                    $string .= '<input name="Product[id]" class="form-control" type="hidden" value="'.$data->id.'" />';
                    $string .= '<input name="Product[price]" class="form-control" type="text" value="'.$data->price.'" />';
                    $string .= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'style' => 'margin-top: 5px;']);
                    $string .= '</form>';
                    return $string;
                }

            ],
            [
                'attribute'=>'category_id',
                'filter'=>Category::find()->select(['name','id'])->indexBy('id')->column(),
                'value'=>'category.name'
            ],
            'position',
            'code',
            //'amount',
            [
                'filter'=>[0=>'Нет в наличии', 1=>'В наличии'],
                'attribute'=>'amount',
                'format' => 'raw',
                'value' => function($data){
                //return $arr[$data->amount];
                    if($data->amount==1)
                        return "В наличии";
                    else
                        return "Нет в наличии";
                }
            ],
            // top
            [
                'filter'=>[0=>'Не в топ товарах', 1=>'В топ товарах'],
                'attribute'=>'top',
                'format' => 'raw',
                'value' => function($data){
                    if($data->top==1)
                        return "<i class=\"fa fa-check\" aria-hidden=\"true\"></i>";
                    else
                        return "<i class=\"fa fa-times\" aria-hidden=\"true\"></i>";
                }
            ],
            // featured
            [
                'filter'=>[0=>'Не в новынках', 1=>'В новинках'],
                'attribute'=>'featured',
                'format' => 'raw',
                'value' => function($data){
                    if($data->news==1)
                        return "<i class=\"fa fa-check\" aria-hidden=\"true\"></i>";
                    else
                        return "<i class=\"fa fa-times\" aria-hidden=\"true\"></i>";
                }
            ],

[
                'filter'=>[0=>'Не в новынках', 1=>'В новинках'],
                'attribute'=>'news',
                'format' => 'raw',
                'value' => function($data){
                    if($data->news==1)
                        return "<i class=\"fa fa-check\" aria-hidden=\"true\"></i>";
                    else
                        return "<i class=\"fa fa-times\" aria-hidden=\"true\"></i>";
                }
            ],
            // 'discount',
            // 'main_img',
            // 'photos:ntext',
            // 'desc:ntext',
            // 'seo_keys:n',
            // 'about_brand:ntext',
            // 'category_id',
            // 'seo_title',text',
            // 'seo_desc:ntext',
            // 'alias',


        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/yii2-app/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Product */

$this->title = 'Редактирование товара: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Товары', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="product-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>