frontend/controllers/CartController.php
<?php

namespace frontend\controllers;
use frontend\models\OrderForm;
use yii\helpers\Json;
use frontend\components\Cart;
use Yii;
use common\models\Product;
use frontend\components\NovaPoshta;
use common\models\ThemeSettings;

class CartController extends \yii\web\Controller
{
    public $layout="mystock";
    public function actionIndex()
    {
        $ids=Yii::$app->session->get('ids');
        $products=(new Product)->findProductsByIds($ids);
        return $this->render('index',[
            'products'=>$products,
            'ids'=>$ids,
            'theme'         => ThemeSettings::findOne(['id'=>1]),
        ]);
    }
    public function actionOrder()
    {
        if(!Yii::$app->session->has('ids'))
            $this->redirect(['index']);
        $model=new OrderForm();
        $thanks = 0;
        if ($model->load(Yii::$app->request->post()) && $model->validate()) 
        {
            if($model->saveOrder())
                $thanks=1;
            return $this->render('order',[
                'model'=>$model,
                'thanks'=>$thanks,
                'theme'         => ThemeSettings::findOne(['id'=>1]),
            ]);
        }
        return $this->render('order',[
            'model'=>$model,
            'cityes'=>(new NovaPoshta())->getCityes(),
            'thanks'=>$thanks,
            'theme'         => ThemeSettings::findOne(['id'=>1]),
        ]);
    }
    public function actionGetoffice($city)
    {
      echo Json::encode((new NovaPoshta())->getOffices($city));
    }
    public function actionAddtocart($id, $amount=1, $size)
    {
        $cart = new Cart();
        if($amount>=1 && $size)
        {
            $cart->addToCart($id, $amount, $size);
            //return $this->redirect(Yii::$app->request->referrer);
            return $this->redirect(['index']);
            /*echo Json::encode(['price'=>Yii::$app->session->get('price'),
            'count'=>Yii::$app->session->get('count'),
            ]);*/
        }
        else
            return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionPluscart($id,$size,$i)
    {
        $cart = new Cart();
        $cart->addToCart($id, 1, $size);
        echo Json::encode(['price'=>Yii::$app->session->get('price'),
            'count'=>Yii::$app->session->get('count'),
            'onecount'=>Yii::$app->session->get('ids')[$i]['count'],
            'oneprice'=>Product::find()->where(['id'=>$id])->one()->r_price
            ]);
    }
     public function actionMinuscart($id,$size,$i)
    {
        $cart = new Cart();
        if(Yii::$app->session->get('ids')[$i]['count']>=2)
            $cart->minusCart($id, $size);
        echo Json::encode(['price'=>Yii::$app->session->get('price'),
            'count'=>Yii::$app->session->get('count'),
            'onecount'=>Yii::$app->session->get('ids')[$i]['count'],
            'oneprice'=>Product::find()->where(['id'=>$id])->one()->r_price
            ]);
    }


    public function actionDelcart($id, $size)
    {
        //if(Yii::$app->session->has('pay_id'))
            //Yii::$app->session->remove('pay_id');
        $cart = new Cart();
        $cart->delFromCart($id, $size);
        return $this->redirect(Yii::$app->request->referrer);
    }
    public function actionUnset()
    {
        Yii::$app->session->remove('ids');
        Yii::$app->session->remove('count');
        Yii::$app->session->remove('price');
        return $this->redirect(['main/index']);
    }
}

frontend/views/cart/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Корзина '.$theme->shop_name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container cart">
    <div class="row titleh1">
        <div class="col-sm-12">
            <hr />
            <h1>Корзина</h1>
        </div>
    </div>
    <?php if($ids) {?>
    <div class="row steps">
        <div class="col-sm-12">
            <div class="step1">1 Корзина</div>
            <div class="step2"><a href="<?=Url::toRoute(['cart/order']);?>">2 Личные данные</a></div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
              <table class="table prodtable"> 
                <thead> 
                    <tr> 
                        <th>Фото</th> 
                        <th>Товар</th> 
                        <th>Цена</th> 
                        <th>Количество</th> 
                        <th>Сумма</th> 
                        <th></th> 
                    </tr> 
                </thead> 
                <tbody> 
                    <?php $i=0; foreach($products as $prod){?>
                    <tr> 
                        <td><a href="<?=Url::toRoute(['main/product', 'alias'=>$prod->alias]);?>"><img src="/frontend/web/mt/img/<?=$prod->main_img;?>"/></a></td> 
                        <td>
                            <div class="cartinfo">
                                <h4><a href="<?=Url::toRoute(['main/product', 'alias'=>$prod->alias]);?>"><?=$prod->name;?></a></h4>
                                <span class="code">Код товара: <?=$prod->code;?></span>
                                <span class="size">РАЗМЕР: <?=$ids[$i]['size'];?></span>
                            </div>
                        </td> 
                        <td class="price"><?=$prod->r_price;?> грн.</td> 
                        <td>
                            <div class="counter">
                                <span class="minus" onclick="cartminus(<?=$prod->id;?>, '<?=$ids[$i]['size'];?>', <?=$i;?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')">-</span>
                                <span id="c_amount<?=$i;?>" class="count"> <?=$ids[$i]['count'];?> </span>
                                <span class="plus" onclick="cartplus(<?=$prod->id;?>, '<?=$ids[$i]['size'];?>', <?=$i;?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')">+</span>
                            </div>    
                        </td> 
                        <td id="stoimost<?=$i;?>" class="price"><?=$prod->r_price*$ids[$i]['count'];?> грн.</td> 
                        <td><a href="<?=Url::toRoute(['cart/delcart', 'id'=>$prod->id, 'size'=>$ids[$i]['size']]);?>"><span class="glyphicon glyphicon-remove del" aria-hidden="true"></span></a></td> 
                    </tr>
                    <?php $i++; }?>
                </tbody> 
              </table>
            </div>
        </div>
    </div>
    <div class="row totalcart tcm">
        <div class="col-sm-12">
            <hr />
            <p class="itogo">Итого</p>
            <div class="clear"></div>
            <p class="counttext"><span id="tot_count"><?=Yii::$app->session->get('count');?></span> товара на сумму:</p>
            <p class="price" id="tot_sum"><?=Yii::$app->session->get('price');?> грн.</p>
        </div>
    </div>
    <div class="row totalcart">
        <div class="col-lg-2 col-md-3 col-sm-4 cont">
            <a href="<?=Url::toRoute(['main/catalog']);?>">Продолжить покупки</a>
        </div>
        <div class="col-lg-2 col-lg-offset-8 col-md-3 col-md-offset-6 col-sm-4 col-sm-offset-4 toorder">
            <a href="<?=Url::toRoute(['cart/order']);?>">Оформить заказ</a>
        </div>
    </div>
    <?php } else {?>
        <div class="row">
            <div class="alert alert-danger" style="text-align:center;" role="alert">В корзине пока что нету товаров...</div>
        </div>
    <?php }?>
</div>

frontend/views/cart/order.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;
use yii\widgets\Pjax;
$this->title = 'Заказ '.$theme->shop_name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container cart">
    <div class="row titleh1">
        <div class="col-sm-12">
            <hr />
            <h1>Заказ</h1>
        </div>
    </div>
    <div class="row steps">
        <div class="col-sm-12">
            <div class="step3"><a href="<?=Url::toRoute(['cart/index']);?>">1 Корзина</a></div>
            <div class="step4">2 Личные данные</div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="row contentorder">
        <?php //Pjax::begin();?>
        <div class="col-md-8">
        <?php $form = ActiveForm::begin(/*['options' => ['data-pjax' => '1']]*/); ?>
            <div class="row formblock">
                <div class="col-sm-6">
                    <?= $form->field($model, 'name')->textInput(['placeholder' => 'Ваше ФИО']) ?>
                    <?= $form->field($model, 'phone')->textInput(['placeholder' => 'Ваш телефон']) ?>
                </div>
                <div class="col-sm-6">
                    <?= $form->field($model, 'city')->textInput(['placeholder' => 'Ваш город', 'data-href' => Url::to(['/cart/getoffice'], true)]); ?>
                    

                    <?= $form->field($model, 'ofice')->dropDownList(
                        $params = [
                        'prompt' => 'Выберите отделение...'
                        ]
                    ); ?>

                </div>
            </div>
            <div class="form-group o_form_butt">
                <?= Html::submitButton('Отправить', [ 'name' => 'contact-button']) ?>
            </div>
            <div class="clear"></div>
        <?php ActiveForm::end(); ?>
        <?php
if($thanks == 1) 
{
    $this->registerJs(' 
    $(document).ready(function() { 
    $("#thanks").modal("show"); 
    });');    
}
?>
<div class="modal fade" id="thanks" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <p class="mod1">Спасибо!</p>
        <p class="mod2">Ваша заявка принята</p>
        <p class="mod3">Менеджер свяжется с вами в ближайшее время</p>
        <p class="mod4">С уважением, команда "Store Kids"</p>
        <button data-href="<?= Url::to('@web/cart/unset', true); ?>" class="modbutt" data-dismiss="modal" aria-label="Close">Закрыть</button>
      </div>
    </div>
  </div>
</div>
        <?php //Pjax::end();?>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="orderinfo">
                <p class="order_title">Ваш заказ:</p>
                <p class="order_desc"><?=Yii::$app->session->get('count');?> товара на сумму: <span><?=Yii::$app->session->get('price');?> грн.</span></p>
                <hr />
                <p class="order_itogo">Итого: <span><?=Yii::$app->session->get('price');?> грн.</span></p>
            </div>
        </div>
    </div>
</div>