frontend/controllers/MainController.php
<?php

namespace frontend\controllers;
use common\models\Product;
use common\models\ProductComment;
use common\models\ProductAttribute;
use common\models\Category;
use common\models\Slider;
use frontend\models\Search;
use common\models\ThemeSettings;
use Yii;
use yii\helpers\Html;
use yii\helpers\Json;

class MainController extends \yii\web\Controller
{
    public $layout = "mystock";

    public $param = 'value';

    /**
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        /** models */
        $slider     = \Yii::createObject(Slider::className());
        $product    = \Yii::createObject(Product::className());
        $search     = \Yii::createObject(Search::className());
        $category   = \Yii::createObject(Category::className());

        /** init variables */
        $slider = $slider->getSlides();
        $slider_top_products = $product->getTop();
        $categories = $category->getHome();

        if ($search->load(Yii::$app->request->post())) {
            return $this->redirect(['search', 'q'=>Html::encode($search->q)]);
        }

        return $this->render('index',[
            'slider'        => $slider,
            'categories'    => $categories,
            'top'           => $slider_top_products,
            'theme'         => ThemeSettings::findOne(['id'=>1]),
        ]);
    }
    
    public function actionProduct($alias)
    {
        $modelComment = new ProductComment();
        if ($modelComment->load(Yii::$app->request->post())) {
            if ($modelComment->save()) {
                $modelComment = new ProductComment();
                $this->refresh();
            }
        }
        $model = (new Product)->getProd($alias);
        $slider1 = (new Product)->getTop();
        $slider2 = (new Product)->getFeatured();
        $slider3 = (new Product)->getNews();return $this->render('product', [
            'comment'   => $modelComment,
            'prod'      => $model,
            'top'       => $slider1,
            'featured'  => $slider2,
            'news'      => $slider3,
        ]);
    }
    
    public function actionCatalog($id)
    {
        $query = Yii::$app->getRequest()->get();

        $productAttributeModel = new ProductAttribute();
        $productModel = new Product();

        /** filter */
        if (isset($query['type'])) {
            $model = $productModel->getFilterProduct($query);
        } else {
            $model = $productModel->getAllinAlias($id);
        }

        $cat = (new Category)->getAll();
        $category=Category::findOne(['id'=>$id]);
        return $this->render('catalog', [
            'products' => $model['products'],
            'attribute' => $productAttributeModel,
            'cat' => $cat,
            'pagination'=>$model['pagination'],
            'category'=>$category
        ]);
    }
    public function actionSearch($q)
    {
        if($q) $products=(new Product())->getAllinSearch($q);
        return $this->render('search',[
            'products' => $products['products'],
            'q'=>$q,
            'pagination'=>$products['pagination']
        ]);
    }
    public function actionAddtowishlist($id)
    {
        $ids=Yii::$app->request->cookies->getValue('wishlist');
        $ids[]=$id;
        Yii::$app->response->cookies->add(new \yii\web\Cookie([
            'name' => 'wishlist',
            'value' =>array_unique($ids),
        ]));
        
        echo Json::encode(['flag'=>'1']);
    }
    public function actionDelfromwishlist($id)
    {
        $ids=Yii::$app->request->cookies->getValue('wishlist');
        $new_arr=[];
        foreach($ids as $oid)
        {
            if($oid!=$id)
            {
               $new_arr[]=$oid;
            }
        }
        Yii::$app->response->cookies->add(new \yii\web\Cookie([
            'name' => 'wishlist',
            'value' =>$new_arr
        ]));
        
        echo Json::encode(['flag'=>'1']);
    }
    /*public function actionTest()
    {
        //echo Yii::$app->getSecurity()->generatePasswordHash('ilovelife888');
        echo Yii::$app->mailer
                ->compose()
                ->setFrom([Yii::$app->params['supportEmail']=>'MY STOCK'])
                ->setTo('siegigor@gmail.com')
                ->setSubject('Новый заказ!')
                ->setHtmlBody("<h1>Новый заказ в интернет-магазине MY STOCK!</h1>")
                ->send();
    }*/
    public function actionDelivery()
    {
        return $this->render('delivery',[
            'theme'=>ThemeSettings::findOne(['id'=>1])
        ]);
    }
    public function actionAbout()
    {
        return $this->render('about',[
            'theme'=>ThemeSettings::findOne(['id'=>1])
        ]);
    }
    public function actionWishlist()
    {
        $ids=Yii::$app->request->cookies->getValue('wishlist');
        $products=(new Product())->findProductsByOrderIds($ids);
        return $this->render('wishlist', [
            'products'=>$products,
            'theme'         => ThemeSettings::findOne(['id'=>1]),
        ]);
    }
    
    public function actionContacts()
    {
        return $this->render('contacts',[
            'theme'=>ThemeSettings::findOne(['id'=>1])
        ]);   
    }
    
    public function actionReturn()
    {
        return $this->render('return',[
            'theme'=>ThemeSettings::findOne(['id'=>1])
        ]);   
    }
}

frontend/views/main/about.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title=$theme->seo_about_title;

$this->registerMetaTag([ 
    'name'=>'description', 
    'content'=>$theme->seo_about_desc
]); 
$this->registerMetaTag([ 
    'name'=>'keywords', 
    'content'=>$theme->seo_about_keys
]);
$this->params['breadcrumbs'][] = 'О нас';
?>

<div class="container aboutus">
    <div class="row">
        <div class="col-sm-12">
            <?=$theme->about_page;?>
        </div>
    </div>
</div>

frontend/views/main/catalog.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager; //виджет для пагиинации что б передавать в скл запрос смещение и лимит
use yii\widgets\Pjax;
$this->title = ($category->seo_title) ? $category->seo_title : "Все товары";

/** breadcrumbs */
$category_breadcrumbs = $category;
$breadcrumbs = true;

while($breadcrumbs) {
    $this->params['breadcrumbs'][] = [
        'label' => $category_breadcrumbs->name,
        'url'   => Url::toRoute(['main/catalog', 'id' => $category_breadcrumbs->id]),
    ];

    $parent = $category_breadcrumbs->parent;
    if ($parent) {
        $category_breadcrumbs = $category_breadcrumbs->find()->where(['id' => $parent])->one();
    } else {
        $breadcrumbs = false;
    }
}
asort($this->params['breadcrumbs']);

$this->registerMetaTag([ 
    'name'=>'description', 
    'content'=>$category->seo_desc
]); 
$this->registerMetaTag([ 
    'name'=>'keywords', 
    'content'=>$category->seo_keys
]);
?>

<div class="container">
    <h1 class="text-center"><?php echo $category->name ?></h1>
    <?php if($category->banner_img){?>
    <div class="catalog" style="text-align: center;">
        <?php if($category->banner_link){?>
             <a href="<?= $category->banner_link ?>" title="" target="_blank" style="width:100%;"><img src="<?php echo Url::to('@web/mt/img/'.$category->banner_img, true); ?>" style="width:100%;"></a>
        <?php } else {?>
             <img src="<?php echo Url::to('@web/mt/img/'.$category->banner_img, true); ?>" style="width:100%;">
        <?php }?>
    </div>
    <?php }?>
    <div class="row">
        <div class="<?= ($category->desc ? 'text' : '') ?> col-lg-12 col-md-12 col-sm-12 hidden-xs">
            <?php if ($category->desc): ?>
                <p><?= $category->desc; ?></p>
                <a href="" id="text-collapse">Читать далее</a>
            <?php else: ?>
                <p>Описание отсутствует</p>
            <?php endif; ?>
        </div>
        <div class="<?= ($category->desc ? 'text' : '') ?> visible-xs col-xs-12">
            <?php if ($category->desc): ?>
                <p class="text-collapse"><?= $category->desc; ?></p>
            <?php else: ?>
                <p>Описание отсутствует</p>
            <?php endif; ?>
        </div>
    </div>
    <div class="row">    
        <div class="col-lg-12 col-md-12 col-sm-12-col-xs-12">
            <div class="filter">
                <div class="title">Фильтровать по: <i class="fa fa-sort-amount-desc visible-xs" aria-hidden="true"></i></div>
                <ul class="hidden-xs">
                	<i class="fa fa-times visible-xs"></i>
                    <?php foreach ($attribute->getAll(false) as $number => $attribute): ?>
                        <li class="hasSub">
                            <a href=""><?= $attribute->name; ?></a>

                            <?php $attributeValues = $attribute->productAttributeValueModel->find()->where(['id_attribute' => $attribute->id])->all(); ?>
                            <div class="float-sub">
                                <?php foreach ($attributeValues as $number_value => $value): ?>
                                    <?php if ($number_value != 0 && $number_value % 4 == 0): ?>
                                        </ul>
                                    <?php endif; ?>
                                    <?php if ($number_value == 0 || $number_value % 4 == 0): ?>
                                        <ul>
                                    <?php endif; ?>
                                    <li>
                                        <a href="<?= Url::toRoute(['main/catalog','id' => $category->id, 'type' => 'attr', 'attr_id' => $attribute->id, 'attr_value_id' => $value->id]); ?>" title="<?= $value->value; ?>"><?= $value->value; ?></a></i>
                                    </li>
                                <?php endforeach; ?>
                            </div>

                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>

        <?php if($products){?>
        <div class="col-md-12 col-sm-12 col-xs-12 catalog_prod">
            <div class="b-items">
                <?php $i = 0; foreach ($products as $prod) {  ?>
                    <div class="b-items-item">
                        <a href="<?= Url::toRoute(['main/product', 'alias' => $prod->alias]); ?>" title="<?= $prod->name; ?>">                           
                            <div  class="img">
                            	<img src="<?php echo Url::to('@web/mt/img/'.$prod->main_img, true); ?>"/>
                        	</div>
	                        <?php if ($prod->discount) { ?>
	                            <div class="discount">- <?= $prod->discount; ?>%</div>
	                        <?php } ?>
	                        
	                        <div class="b-items-bottom">
	                            <div class="title">
	                                <?= $prod->name; ?>
	                            </div>
	                            <div class="prod_price">                  
	                                
                                    <?php if ($prod->discount) { ?>
                                        <strike class="prod_old_price"><?= $prod->price; ?> грн.</strike>
                                    <?php } ?>
                                    <div class="<?php echo ($prod->discount ? 'new' : '')?>"><?= $prod->r_price; ?> грн.</div>
	                            </div>
	                            <div class="links">
	                                <a class="left towish" href="#" onclick="towishlist(event, <?= $prod->id; ?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')" tabindex="0">
	                                    <span class="save">
                                            <i class="icon icon-heart"></i>
	                                       <span>В избранное</span>
                                        </span>
                                        
	                                </a>
                                    <a href="#" class="fromwish hidden" onclick="delfromwishlist(event, <?= $prod->id; ?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')">
                                        <span class="remove"><i class="icon icon-heart-broken"></i> Отменить</span>
                                    </a>
	                                <a href="<?= Url::toRoute(['main/product', 'alias' => $prod->alias], true); ?> " title="<?= $prod->name; ?>">
	                                    <i class="icon icon-shoppingbasket"></i>
	                                    <span>Купить сейчас</span>
	                                </a>
	                            </div>
	                        </div>
                    	</a>
                    </div>
                    
                <?php } ?>
            </div>
            <div class="row">
                <div class="col-sm-12 pag">
                    <?php if($pagination) {?>
                        <div id="pages" style="text-align: center;">
                            <?=LinkPager::widget([
                                'pagination'=>$pagination,
                                //'firstPageLabel'=>'В начало',
                                //'lastPageLabel'=>'В конец',
                                'prevPageLabel'=>'<i class="fa fa-angle-left" aria-hidden="true"></i> Назад',
                                'nextPageLabel'=>'Вперед <i class="fa fa-angle-right" aria-hidden="true"></i>'
                            ]);?>
                        </div>
                    <?php }?>
                </div>
            </div>
            <?php } else {?>
            <div class="col-md-9  catalog_prod">
                <div class="alert alert-warning" role="alert">Извините, но пока что нет товаров в этой категории</div>
            </div>
            <?php }?>
        </div>
    </div>
</div>
<div class="modal fade" id="added" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <p class="mod1">Добавленно!</p>
        <button  class="modbutt" data-dismiss="modal" aria-label="Close">Закрыть</button>
      </div>
    </div>
  </div>
</div>

frontend/views/main/delivery.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title=$theme->seo_delivery_title;

$this->registerMetaTag([ 
    'name'=>'description', 
    'content'=>$theme->seo_delivery_desc
]); 
$this->registerMetaTag([ 
    'name'=>'keywords', 
    'content'=>$theme->seo_delivery_keys
]);
$this->params['breadcrumbs'][] = 'Оплата и доставка';
?>
<div class="container delivery">
    <div class="row">
        <div class="col-sm-12">
            <?=$theme->delivery_page;?>
        </div>
    </div>
</div>

frontend/views/main/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = $theme->seo_main_title;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $theme->seo_main_desc
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $theme->seo_main_keys
]);
?>
<div class="container">
        <div class="phones visible-xs">
            <a href="tel:<?= $theme->phone1; ?>"><?= $theme->phone1; ?></a>
            <a href="tel:<?= $theme->phone1; ?>"><?= $theme->phone2; ?></a>
        </div>
    <?php if ($slider): ?>        
        <div class="banner" id="banner">
            <?php $i=0; foreach ($slider as $number => $slide): ?>
                <div class="item <?php echo ($i==0 ?  'active' : '') ?>" style="background-image: url('<?= Url::to('@web/mt/img/'.$slide->img, true); ?>');">                        
                </div>
            <?php $i++; endforeach; ?>
        </div>
    <?php endif; ?>
        
    <!--<div class="indexTab Top">

        <div class="row back_fon">
            <div class="col-md-12">
                <div class="strip">
                    <h2>Отличники StoreKids</h2>
                </div>
            </div>
        </div>

        <div class="owl-carousel">
            <?php $i = 0; foreach ($top as $prod) { ?>
            <div class="b-items-item">
                    <a href="<?= Url::toRoute(['main/product', 'alias' => $prod->alias]); ?>" title="" class="img">
                        <img src="<?php echo Url::to('@web/mt/img/'.$prod->main_img, true); ?>"/>
                    </a>
                    <?php if ($prod->discount) { ?>
                        <div class="discount">- <?= $prod->discount; ?>%</div>
                    <?php } ?>
                    
                    <div class="b-items-bottom">
                        <div class="title">
                            <a href="<?= Url::toRoute(['main/product', 'alias' => $prod->alias]); ?>" title="">
                                <?= $prod->name; ?>                                
                            </a>
                        </div>
                        <?php if ($prod->discount) { ?>
                            <strike class="prod_old_price"><?= $prod->price; ?> грн.</strike>
                        <?php } ?>
                        <div class="prod_price <?php echo ($prod->discount ? 'new' : '')?>"><?= $prod->r_price; ?> грн.</div>
                        <div class="links">
                            <a href="#" onclick="towishlist(event, <?= $prod->id; ?>)" tabindex="0">
                                <i class="icon icon-heart"></i>
                                <span>В избранное</span>
                            </a>
                            <a href="<?= Url::toRoute(['main/product', 'alias' => $prod->alias], true); ?>">
                                <i class="icon icon-shoppingbasket"></i>
                                <span>Купить сейчас</span>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div> -->

    <?php if ($categories): ?>
        <div class="categories">
            <?php foreach ($categories as $number => $category): ?>
                <?php if ($category->parent === 0): ?>
                    <div class="item">
                        <a href="<?= Url::toRoute(['main/catalog', 'id' => $category->id]); ?>" title="<?= $category->name; ?>">
                            <div class="img">
                                <img src="<?php echo Url::to('@web/mt/img/'.$category->cat_img, true); ?>">
                            </div>
                            <div class="content">
                                <h4><?= $category->name; ?></h4>
                                <div class="desc">Финальная распродажа</div>
                            </div>
                        </a>    
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>    

</div>

<div class="modal fade" id="added" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <p class="mod1">Добавленно!</p>
                <button class="modbutt" data-dismiss="modal" aria-label="Close">Закрыть</button>
            </div>
        </div>
    </div>
</div>

frontend/views/main/product.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;

$this->title = $prod->seo_title;
$this->params['breadcrumbs'][] = ['label' => $prod->category->name, 'url' => ['main/catalog', 'alias' => $prod->category->alias]];
$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $prod->seo_desc
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $prod->seo_keys
]);
?>
<style>
    .fotorama img {
        max-width: 458px;
    }
</style>

<div class="container oneproduct">
    <!--<a href="<?= Url::toRoute(['main/catalog', 'alias' => $prod->category->alias]); ?>" class="goback">< Вернуться назад</a>-->
    <div class="row rowprod">
        <div class="col-lg-7 col-md-6 col-sm-6">
            <div class="littprodslider">
                <div class="fotorama" data-allowfullscreen="false" data-maxwidth="525" data-width="100%" data-thumbwidth="113"
                     data-thumbheight="115" data-nav="thumbs" data-arrows="true" data-click="true" data-swipe="true">
                    <a href="<?= Url::to('@web/mt/img/'.$prod->main_img, true); ?>"><img src="<?= Url::to('@web/mt/img/'.$prod->main_img, true); ?>"/></a>
                    <?php if (count($prod->photos) >= 1) {
                        foreach (explode("##", $prod->photos) as $photo) { ?>
                            <a href="<?= Url::to('@web/mt/img/'.$photo, true); ?>"><img src="<?= Url::to('@web/mt/img/'.$photo, true); ?>"/></a>
                        <?php }
                    } ?>
                </div>
            </div>
            <div class="bigprodslider">
                <ul id="etalage">
                    <li>
                        <a href="<?= Url::to('@web/mt/img/'.$prod->main_img, true); ?>">
                            <img class="etalage_source_image" src="<?= Url::to('@web/mt/img/'.$prod->main_img, true); ?>"/>
                            <img class="etalage_thumb_image" src="<?= Url::to('@web/mt/img/'.$prod->main_img, true); ?>"/>
                        </a>
                    </li>
                    <?php if (count($prod->photos) >= 1) {
                        foreach (explode("##", $prod->photos) as $photo) {
                            if ($photo) { ?>
                                <li>
                                    <a href="<?= Url::to('@web/mt/img/'.$photo, true); ?>">
                                        <img class="etalage_source_image" src="<?= Url::to('@web/mt/img/'.$photo, true); ?>"/>
                                        <img class="etalage_thumb_image" src="<?= Url::to('@web/mt/img/'.$photo, true); ?>"/>
                                    </a>
                                </li>
                            <?php }
                        }
                    } ?>
                    <?php if ($prod->discount) { ?>
                        <span class="discount">-<?= $prod->discount; ?>%</span>
                    <?php } ?>
                </ul>
                <div class="hidden"><div id="zoom"></div></div>
                
            </div>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-6 prodinfo">

            <div class="col-sm-112">
                <h1><?= $prod->name; ?></h1>
            </div>
            <div class="prices col-lg-12 col-md-12 col-sm-12">
                <?php if ($prod->discount) { ?>
                    <span class="price full"><?= $prod->price ?> грн.</span>
                    <span class="price sale"><?= $prod->r_price; ?> грн.</span>
                <?php } else { ?>
                    <span class="price"><?= $prod->price; ?> грн.</span>
                <?php } ?>
                <span class="instock">
                    <?php if ($prod->amount > 0) { ?>
                        В наличии
                    <?php } else { ?>
                        Нет в наличии
                    <?php } ?>
                </span>
            </div>
            <div class="purchase">
                <select class="onesize" name="id" style="display: none;">
                	<option value="-1" disabled="disabled" selected="selected">Выберите размер</option>
                	<?php if (!empty(explode(", ", $prod->sizes))): ?>
	                	<?php $i = 0; foreach (explode(", ", $prod->sizes) as $size): ?>
		                    <option value="<?= $size; ?>" data-id="<?= $i ?>">
		                        <?=$size;?>
		                    </option>
	                	<?php $i++; endforeach; ?>
	                <?php endif; ?>	
                </select>
                <div id="id-slct" class="slct" tabindex="0">
                    <div class="status"><span>Choose variant</span>
                        <i class="icon"></i>
                    </div>
                    <ul class="list">                        
                    </ul>
                </div>
                <a class="buy" href="<?= Url::toRoute(['cart/addtocart', 'id' => $prod->id]); ?>&size=">Купить</a>
            </div>

            <div class="product-actions">
                <div class="action favorite">
                    <a href="" class="towish" onclick="towishlist(event, <?= $prod->id; ?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')">
                        <span class="save"><i class="icon icon-heart-small"></i>  В избранное</span>
                    </a>
                    <a href="" class="fromwish hidden" onclick="delfromwishlist(event, <?= $prod->id; ?>, '<?= Url::to(Yii::$app->homeUrl, true); ?>')">
                        <span class="remove"><i class="icon icon-heart-broken-small"></i> Отменить</span>
                    </a>
                </div>               
                                                
                <div class="action comment">
                    <a href="#comment" data-disqus-identifier="/mllotte-woven-pant-black/p/146651">
                        <i class="icon icon-comments"></i> Комментарии
                    </a>
                </div>
            </div>

            <div class="description">
                <?= $prod->desc; ?>
            </div>

            <ul class="product-properties">        
                    
                <li class="item-no">
                    Код товара: <?= $prod->code; ?>
                </li>
            </ul>

        </div>
    </div>
</div>

<div class="container">
    <?php Pjax::begin();?>
        <!-- comment -->
        <div class="product-comment-form" id="comment">
            <div class="title">
                <span>0 Комментариев</span>
            </div>
            <div class="actions">
                <ul>
                    <li>
                        <div class="thread-likes">
                            <a href="#" id="recommend" title="Recommend this discussion" class="dropdown-toggle upvoted">
                                <span class="icon-heart"></span>
                                <span class="recommend">Рекомендовать</span>
                                <span class="recommended hidden">Рекомендуется</span>
                                <span class="label label-count hidden">1</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu--coachmark">
                                <li>
                                    <h2 class="coachmark__heading">Обсуждение рекомендовано!</h2>
                                    <p class="coachmark__description">Рекомендация означает, что этим обсуждением стоит поделиться.</p>
                                    <a href="https://disqus.com/home/?utm_source=disqus_embed&amp;utm_content=recommend_btn" class="btn btn-primary coachmark__button" target="_blank">
                                        Найти больше обсуждений
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li id="thread-share-menu" class="nav-tab nav-tab--secondary dropdown share-menu hidden-sm" data-dropdown="enabled">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Share" data-tid="74">
                            <span class="icon-export"></span>
                            <span class="share">Поделиться</span>
                        </a>
                        <ul class="share-menu dropdown-menu">
                            <li>
                                <div class="share-menu__label">Поделиться обсуждением в:</div>
                                <ul>
                                    <li class="twitter">
                                        <a data-action="share:twitter" href="#">Twitter</a>
                                    </li>
                                    <li class="facebook">
                                        <a data-action="share:facebook" href="#">Facebook</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]);?>
                    <?= $form->field($comment, 'id_product')->hiddenInput(['value' => $prod->id])->label(false) ?>

                    <?= $form->field($comment, 'comment')->textarea(['placeholder' => 'Введите ваш комментарий', 'class' => 'form-control'])->label(false) ?>
    
                    <?= $form->field($comment, 'name')->textInput(['placeholder' => 'Введите ваше имя', 'class' => 'form-control'])->label(false) ?>
    
                    <div class="form-group">
                        <?= Html::submitButton('<span class="icon-proceed"></span>', ['class' => 'proceed__button']) ?>
                    </div>
            <?php ActiveForm::end(); ?>
        </div>

        <?php if ($comment_list = $comment->getCommentsByProductId($prod->id)): ?>
            <div class="product-comment-list">
                <ul>
                    <?php foreach ($comment_list as $number => $comment): ?>
                        <li>
                            <div class="comment-header">
                                <span class="author"><?= $comment->name; ?></span>
                                <!--<span class="bullet time-ago-bullet" aria-hidden="true">•</span>
                                <span class="time">час назад</span>-->
                            </div>
                            <div class="comment-body">
                                <?= $comment->comment; ?>
                            </div>
                            
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php else: ?>
            <div class="alert alert-warning" role="alert">Извините, но пока что нет комментариев для этого товара.</div>
        <?php endif; ?>
        <!-- /comment -->
    <?php Pjax::end();?>

</div>

<div class="modal fade" id="added" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <p class="mod1">Добавленно!</p>
                <button class="modbutt" data-dismiss="modal" aria-label="Close">Закрыть</button>
            </div>
        </div>
    </div>
</div>

frontend/views/main/return.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title=$theme->seo_return_title;

$this->registerMetaTag([ 
    'name'=>'description', 
    'content'=>$theme->seo_return_desc
]); 
$this->registerMetaTag([ 
    'name'=>'keywords', 
    'content'=>$theme->seo_return_keys
]);
$this->params['breadcrumbs'][] = 'Возврат и обмен';
?>

<div class="container delivery">
        
    <div class="row">
        <div class="col-sm-12">
            <?=$theme->return_page;?>
        </div>
    </div>
</div>